Updated some stuff for the first time in forever

diff --git a/bin/dotfiles b/bin/dotfiles
--- a/bin/dotfiles
+++ b/bin/dotfiles
@@ -8,14 +8,14 @@ export DOTFILES_DIR=$HOME/.dotfiles
 sub_help () {
     echo "Usage: $BIN_NAME <command>\n"
     echo "Commands:"
-    echo "   boot               Installs settings for OS X."
+    echo "   boot               Installs settings for macOS."
     echo "   help               This help message"
     echo "   edit               Open dotfiles in default editor ($EDITOR) and Git GUI ($GIT_GUI)"
     echo "   reload             Reload dotfiles"
     if [ "$(uname)" == "Darwin" ]; then
-				echo "   update             Update OS X Applications, Homebrew (cask), npm, and Ruby packages"
-				echo "   osx                Apply OS X system defaults"
-				echo "   dock               Apply OS X Dock settings"
+				echo "   update             Update macOS Applications and Homebrew (cask) packages"
+				echo "   macos              Apply macOS system defaults"
+				echo "   dock               Apply macOS Dock settings"
     fi
     echo "   go                 Apply go settings"
 }
@@ -44,42 +44,46 @@ sub_update () {
 }
 
 sub_osx () {
-    for DEFAULTS_FILE in "$DOTFILES_DIR"/osx/defaults*.sh; do
-        [ -f "$DEFAULTS_FILE" ] && echo "Applying $DEFAULTS_FILE" && source "$DEFAULTS_FILE"
-    done
-    echo "Done. Some changes may require a logout/restart to take effect."
+		sub_macos
+}
+
+sub_macos () {
+		for DEFAULTS_FILE in "$DOTFILES_DIR"/osx/defaults*.sh; do
+				[ -f "$DEFAULTS_FILE" ] && echo "Applying $DEFAULTS_FILE" && source "$DEFAULTS_FILE"
+		done
+		echo "Done. Some changes may require a logout/restart to take effect."
 }
 
 sub_dock () {
-    source "$DOTFILES_DIR/osx/dock.sh" && echo "Dock reloaded."
+		source "$DOTFILES_DIR/osx/dock.sh" && echo "Dock reloaded."
 }
 
 sub_go () {
-    source "$DOTFILES_DIR/install/go.sh" && echo "go utilies installed."
+		source "$DOTFILES_DIR/install/go.sh" && echo "go utilies installed."
 }
 
 sub_install () {
-    local SCRIPT="${DOTFILES_DIR}/install/${SUB_COMMAND_NAME}.sh"
-    [ -f "$SCRIPT" ] && source "$SCRIPT" || echo "Unable to find script to install ${SUB_COMMAND_NAME}"
+		local SCRIPT="${DOTFILES_DIR}/install/${SUB_COMMAND_NAME}.sh"
+		[ -f "$SCRIPT" ] && source "$SCRIPT" || echo "Unable to find script to install ${SUB_COMMAND_NAME}"
 }
 
 # Make sure to keep this in sync with the available public commands
 
 sub_completion () {
-    echo "help edit reload update osx dock install"
+		echo "help edit reload update osx dock install"
 }
 
 case $COMMAND_NAME in
-    "" | "-h" | "--help")
-        sub_help
-        ;;
-    *)
-        shift
-        sub_${COMMAND_NAME} $@
-        if [ $? = 127 ]; then
+		"" | "-h" | "--help")
+				sub_help
+				;;
+		*)
+				shift
+				sub_${COMMAND_NAME} $@
+				if [ $? = 127 ]; then
 						echo "'$COMMAND_NAME' is not a known command or has errors." >&2
 						sub_help
 						exit 1
-        fi
-        ;;
+				fi
+				;;
 esac
