Clean up stuff after new computer set up, update neovim config install, remove slate configs

diff --git a/bin/dotfiles b/bin/dotfiles
--- a/bin/dotfiles
+++ b/bin/dotfiles
@@ -13,18 +13,19 @@ sub_help () {
     echo "   edit               Open dotfiles in default editor ($EDITOR) and Git GUI ($GIT_GUI)"
     echo "   reload             Reload dotfiles"
     if [ "$(uname)" == "Darwin" ]; then
-				echo "   update             Update macOS Applications and Homebrew (cask) packages"
-				echo "   macos              Apply macOS system defaults"
-				echo "   dock               Apply macOS Dock settings"
+	echo "   update             Update macOS Applications and Homebrew (cask) packages"
+	echo "   macos              Apply macOS system defaults"
+	echo "   dock               Apply macOS Dock settings"
     fi
     echo "   go                 Apply go settings"
+    echo "   python             Installs python packages and libraries."
 }
 
 sub_boot () {
-		echo "Setting up OS X"
-		clear
-		source "$DOTFILES_DIR/install.sh"
-		#	source "$DOTFILES_DIR/install/osx/osx.sh"
+    echo "Setting up OS X"
+    clear
+    source "$DOTFILES_DIR/install.sh"
+    #	source "$DOTFILES_DIR/install/osx/osx.sh"
 }
 
 sub_edit () {
@@ -44,46 +45,50 @@ sub_update () {
 }
 
 sub_osx () {
-		sub_macos
+    sub_macos
 }
 
 sub_macos () {
-		for DEFAULTS_FILE in "$DOTFILES_DIR"/osx/defaults*.sh; do
-				[ -f "$DEFAULTS_FILE" ] && echo "Applying $DEFAULTS_FILE" && source "$DEFAULTS_FILE"
-		done
-		echo "Done. Some changes may require a logout/restart to take effect."
+    for DEFAULTS_FILE in "$DOTFILES_DIR"/osx/defaults*.sh; do
+	[ -f "$DEFAULTS_FILE" ] && echo "Applying $DEFAULTS_FILE" && source "$DEFAULTS_FILE"
+    done
+    echo "Done. Some changes may require a logout/restart to take effect."
 }
 
 sub_dock () {
-		source "$DOTFILES_DIR/osx/dock.sh" && echo "Dock reloaded."
+    source "$DOTFILES_DIR/install/dock.sh" && echo "Dock reloaded."
 }
 
 sub_go () {
-		source "$DOTFILES_DIR/install/go.sh" && echo "go utilies installed."
+    source "$DOTFILES_DIR/install/go.sh" && echo "go utilies installed."
+}
+
+sub_python () {
+    source "$DOTFILES_DIR/install/python.sh" && echo "python utilies installed."
 }
 
 sub_install () {
-		local SCRIPT="${DOTFILES_DIR}/install/${SUB_COMMAND_NAME}.sh"
-		[ -f "$SCRIPT" ] && source "$SCRIPT" || echo "Unable to find script to install ${SUB_COMMAND_NAME}"
+    local SCRIPT="${DOTFILES_DIR}/install/${SUB_COMMAND_NAME}.sh"
+    [ -f "$SCRIPT" ] && source "$SCRIPT" || echo "Unable to find script to install ${SUB_COMMAND_NAME}"
 }
 
 # Make sure to keep this in sync with the available public commands
 
 sub_completion () {
-		echo "help edit reload update osx dock install"
+    echo "help edit reload update osx dock install"
 }
 
 case $COMMAND_NAME in
-		"" | "-h" | "--help")
-				sub_help
-				;;
-		*)
-				shift
-				sub_${COMMAND_NAME} $@
-				if [ $? = 127 ]; then
-						echo "'$COMMAND_NAME' is not a known command or has errors." >&2
-						sub_help
-						exit 1
-				fi
-				;;
+    "" | "-h" | "--help")
+	sub_help
+	;;
+    *)
+	shift
+	sub_${COMMAND_NAME} $@
+	if [ $? = 127 ]; then
+	    echo "'$COMMAND_NAME' is not a known command or has errors." >&2
+	    sub_help
+	    exit 1
+	fi
+	;;
 esac
