Switched to using GNU Stow

diff --git a/bin/dotfiles b/bin/dotfiles
--- a/bin/dotfiles
+++ b/bin/dotfiles
@@ -13,18 +13,18 @@ sub_help () {
     echo "   edit               Open dotfiles in default editor ($EDITOR) and Git GUI ($GIT_GUI)"
     echo "   reload             Reload dotfiles"
     if [ "$(uname)" == "Darwin" ]; then
-	echo "   update             Update OS X Applications, Homebrew (cask), npm, and Ruby packages"
-	echo "   osx                Apply OS X system defaults"
-	echo "   dock               Apply OS X Dock settings"
+				echo "   update             Update OS X Applications, Homebrew (cask), npm, and Ruby packages"
+				echo "   osx                Apply OS X system defaults"
+				echo "   dock               Apply OS X Dock settings"
     fi
     echo "   go                 Apply go settings"
 }
 
 sub_boot () {
-	echo "Setting up OS X"
-	clear
-	source "$DOTFILES_DIR/install.sh"
-#	source "$DOTFILES_DIR/install/osx/osx.sh"
+		echo "Setting up OS X"
+		clear
+		source "$DOTFILES_DIR/install.sh"
+		#	source "$DOTFILES_DIR/install/osx/osx.sh"
 }
 
 sub_edit () {
@@ -77,9 +77,9 @@ case $COMMAND_NAME in
         shift
         sub_${COMMAND_NAME} $@
         if [ $? = 127 ]; then
-	    echo "'$COMMAND_NAME' is not a known command or has errors." >&2
-	    sub_help
-	    exit 1
+						echo "'$COMMAND_NAME' is not a known command or has errors." >&2
+						sub_help
+						exit 1
         fi
         ;;
 esac
